project_root: /home/jha/jha/python_scripts/CRYSTALdataGen

h5_path: data/dataset.h5
export_metadata_json: data/tv_meta.json

train_xyz: data/train.xyz
valid_xyz: data/valid_interp.xyz

rng_seed: 31415

valid_split_mode: fraction
valid_per_composition: 20
valid_fraction_per_composition: 0.10

include_references_in_train: false
export_stress: true
export_dipoles: true
shuffle_final_lists: true

filter_by_training_flag: true
filter_references_by_training_flag: false
allow_small_compositions: true

structure_selection_mode: one
structure_name: Al2O3
structure_names: null

use_structure_suffix_in_output: true

distortion_id_prefix: null
distortion_id_prefixes: null
