structure: AlN_PBE
results_group_dir: AlN_PBE_sc

dry_run: false
smoke_test: false
max_runs: null
max_parallel_trainings: 1

crystal_db_path: data/ref_db.h5
# resume_sweep_dir: results/AlN_PBE_10_90/AlN_PBE_master_eval_full_260518_155033

eval_settings:
  device: cuda
  default_dtype: float64
  frechet: true
  fmax: 1.0e-11
  compare_crystal_modes: true
  crystal_hess_path: null
  crystal_freq_out_path: null
  crystal_hessian_units: hartree/bohr^2
  write_ref_db: true
  ref_db_path: data/ref_db.h5
  use_ref_db_cache: true
  force_reeval: false
  plot_only: false

base_config:
  train_file: sc_train_AlN_PBE_444.xyz
  valid_file: sc_valid_AlN_PBE_49.xyz
  chem: AlN
  atomic_numbers: [7, 13]
  model_type: MACELES
  E0s: average
  batch_size: 2
  valid_batch_size: 2
  max_epochs: 173

sweep_grid:
  seed: [1]
  r_max: [3.0, 3.5, 4.0, 4.5, 5.25, 5.5, 5.75]
  batch_size: [2]
  valid_batch_size: [2]
  energy_weight: [1.0]
  forces_weight: [75, 100.0]
  use_stress: [false]
  stress_weight: [2.0] 
