structure: SiO2
results_group_dir: SiO2_1000_10_90

dry_run: false
smoke_test: false
max_runs: null
max_parallel_trainings: 1

crystal_db_path: data/ref_db.h5

eval_settings:
  device: cuda
  default_dtype: float64
  frechet: true
  fmax: 1.0e-11
  calculator_mode: "0"
  compare_crystal_modes: true
  crystal_hess_path: null
  crystal_freq_out_path: null
  crystal_hessian_units: hartree/bohr^2
  
  compare_crystal_modes: true
  crystal_hess_path: null
  crystal_freq_out_path: null
  crystal_hessian_units: "hartree/bohr^2"

  run_phonopy: false
  phonopy_plugin: null

  write_ref_db: true
  ref_db_path: /home/jha/jha/python_scripts/CRYSTALdataGen/data/ref_db.h5
  

base_config:
  train_file: train_SiO2.xyz
  valid_file: valid_SiO2.xyz
  chem: SiO2
  atomic_numbers: [8, 14]
  model_type: MACELES
  E0s: average
  batch_size: 2
  valid_batch_size: 2
  max_epochs: 173
  energy_weight: 1.0
  forces_weight: 100.0
  r_max: 6.5
  use_stress: false
  stress_weight: 2.0
  default_dtype: float64
  device: cuda
  num_workers: 0
  use_ema: true
  use_swa: false
  restart_latest: false
  run_extraction: true
  overwrite_existing_logs: true
  env:
    OMP_NUM_THREADS: "1"

sweep_grid:
  seed: [1, 2]
  r_max: [2.75, 3.0, 3.25, 3.50, 3.75, 4.0, 4.25]
  batch_size: [2]
  valid_batch_size: [2]
  energy_weight: [1.0, 2.0, 3.0]
  forces_weight: [100.0]
  use_stress: [false]
  stress_weight: [2.0] 
