structure: TiO2_rutil_PBE
results_group_dir: TiO2_rutil_PBE_25_75

dry_run: false
smoke_test: false
max_runs: null
max_parallel_trainings: 1

crystal_db_path: data/ref_db.h5

eval_settings:
  device: cuda
  default_dtype: float64
  frechet: true
  fmax: 1.0e-11
  compare_crystal_modes: true
  crystal_hess_path: null
  crystal_freq_out_path: null
  crystal_hessian_units: hartree/bohr^2
  write_ref_db: true
  ref_db_path: data/ref_db.h5
  use_ref_db_cache: true
  force_reeval: false
  plot_only: false

base_config:
  train_file: train_TiO2_rutil_PBE_1123.xyz
  valid_file: valid_TiO2_rutil_PBE_374.xyz
  chem: TiO2
  atomic_numbers: [8, 22]
  model_type: MACELES
  E0s: average
  batch_size: 2
  valid_batch_size: 2
  max_epochs: 173

sweep_grid:
  seed: [2]
  r_max: [2.75, 3.00, 3.25, 5.5, 6.0, 6.75, 7.0, 7.25, 7.5]
  batch_size: [1]
  valid_batch_size: [1]
  energy_weight: [2.0, 3.0]
  forces_weight: [75.0, 100.0]
  use_stress: [false]
  stress_weight: [2.0] 
