script: mixed_disto_struct.py

root: /home/jha/jha/python_scripts/CRYSTALdataGen
structures_dir: structures_pbe

only: [Al2O3_PBE]

n_structures: 150
rng_seed: 42
charge: "000"

supercell: null
overwrite: true
distortion_mode: "random"

frac_medium_disp: 0.09
frac_mixed: 0.8
frac_small_disp: 0.1
frac_strain_only: 0.01

small_disp_max: 0.05
small_strain_max: 0.01
medium_disp_max: 0.06
medium_strain_max: 0.02

ncores: 5
partition: CPU_rune
rune: 5

shrink: [4, 4]
maxcycle: 500
use_gradcal: true
savewf: false
mulliken: false
functional: PBESOLXC

max_generation_attempts_per_structure: 20000
reject_on_short_distance: true


