script: gen_disto_struct.py

root: /home/jha/jha/python_scripts/CRYSTALdataGen
structures_dir: structures_pbe

only: [SiO2_PBE]

n_structures: 350
rng_seed: 37629
charge: "200"

supercell: null
overwrite: true

disp_max: 0.050
strain_max: 0.010

ncores: 5
partition: CPU_rune
rune: 5

shrink: [4, 4]
maxcycle: 500
use_gradcal: true
savewf: false
mulliken: false
functional: PBESOLXC

max_generation_attempts_per_structure: 20000
reject_on_short_distance: true
